name: PhoneBlock Dongle
version: "0.1.21"
slug: phoneblock_dongle
description: Run the "Phoneblock Dongle" as a Home Assistant App instead of a physical ESP32 Dongle
url: https://github.com/YaannnTech/phoneblock/tree/linux-core-extraction/phoneblock-dongle
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
host_network: true
webui: http://[HOST]:[PORT:8080]/
options: {}
schema: {}
map:
  - type: data
    read_only: false
watchdog: http://[HOST]:8080/health
panel_icon: mdi:phone-alert
