server {
    listen @INGRESS_PORT@;
    server_name _;

    location = /health {
        proxy_pass http://127.0.0.1:8080/health;
    }

    location / {
        allow 172.30.32.2;
        deny all;

        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
    }
}